# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Extension release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14
      uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'npm'
    - run: npm ci
    - run: npm run build:chrome
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.6.2
      with:
        filename: release.zip
        path: dist/chrome
        directory: .
        type: zip
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release.zip
